Header Validation Tests commit
zhyldyzMaks/Solvd-UI pull request #1
Opened 2023-07-28 10:48 UTC by zhyldyzMaks

In this PR:
- Header Validation test cases implemented
- Test Cases validated

2023-07-31 12:48 UTC, vboltrukanis requested changes

2023-07-31 12:48 UTC, vboltrukanis commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/footer/CarinaFooterMenuBase.java
> +public abstract class CarinaFooterMenuBase extends AbstractUIObject {
Whats the point of having this class?

2023-07-31 12:48 UTC, vboltrukanis commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/header/CarinaHeaderPage.java
> +    public boolean isZebRunnerLogoDisplayed() {
I am waiting just for logo to be present, but in your case it also fails if it is not in left, which is unexpected

2023-07-31 12:48 UTC, vboltrukanis commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/header/CarinaHeaderPageBase.java
> +public abstract class CarinaHeaderPageBase extends AbstractUIObject {
What is the usage of this class?

2023-07-31 12:48 UTC, vboltrukanis commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/header/CarinaHeaderPage.java
> +    public String isCarinaBrandDisplayed() {
if method starts with '**is**BLAHBLAH' it means, that answer is Yes-No (Boolean value).
Make sure name of method is corresponding to what it does

2023-07-31 12:48 UTC, vboltrukanis commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/header/CarinaHeaderPage.java
> +    public String getSearchText() {
Text and Placeholder are two different values. Do not confuse others.

2023-07-31 12:48 UTC, vboltrukanis commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/navigation/CarinaNavigationPage.java
> +    public void clickGettingStartedLink() {
That will take too long each time this method is used.
Create a separate method for this exact button if  you believe it is necessary or update the method so it can do more then only clicking this exact button.

2023-07-31 12:48 UTC, vboltrukanis commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/navigation/CarinaNavigationPage.java
> +    public boolean isNavigationLinkListPresent() {
What you did is basically: 
If at least one element of link list is present - true
otherwise false

method name states: 
If list is present - true
otherwise - false

2023-07-31 12:48 UTC, vboltrukanis commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/navigation/CarinaNavigationPage.java
> +    public boolean isHighlighted() {
Page Highlighted? Screen highlighted, be more specific.

2023-07-31 12:48 UTC, vboltrukanis commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/navigation/CarinaNavigationPage.java
> +            if (allNavLinks.get(i).equals(dynamicXpathElement.format("md-nav__item md-nav__item--active")) || allNavLinks.get(i).equals(dynamicXpathElement.format("md-nav__item md-nav__item--active m
Do you believe this is readable?

2023-07-31 12:48 UTC, vboltrukanis commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/navigation/CarinaNavigationPage.java
> +    public boolean areElementsHidden() {
Which elements?
All elements of a page are hidden and you see nothing?

2023-07-31 12:48 UTC, vboltrukanis commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/navigation/CarinaNavigationPage.java
> +    public boolean areNestedElementsRevealed() {
This will not ensure you that all dropdowns are working. 
One parent may be expanded and all other fail -> you will get true.

2023-07-31 12:48 UTC, vboltrukanis commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/navigation/CarinaNavigationPage.java
> +    public void isLinkClickRedirectToProperPage(String expectedLink, String[] lists, boolean nested) {
Bad function name, bad props name

2023-07-31 12:48 UTC, vboltrukanis commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/navigation/CarinaNavigationPage.java
> +                        actualLink = findExtendedWebElement(By.xpath("//a[@title='" + elements.get(k) + "']"));
use ExtendedWebElement.format() method here
https://zebrunner.github.io/carina/automation/web/#:~:text=1)%20Declare%20an%20element%20using%20the%20%40FindBy%20annotation%20and%20specify%20a%20locator%20based%20on%20the%20convention%20used%20by%20the%20Formatter%3A

2023-07-31 12:48 UTC, vboltrukanis commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/navigation/NavigationData.java
> +                {"Overview", new String[]{}, false},
if your list is empty -> third value always false.

2023-07-31 12:48 UTC, vboltrukanis commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/pages/common/GitHubPageBase.java
> +public abstract class GitHubPageBase extends AbstractPage {
What is the usage of this page?

2023-07-31 12:48 UTC, vboltrukanis commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/pages/common/CarinaHomePageBase.java
> +public abstract class CarinaHomePageBase extends AbstractPage {
What is the usage of this page?

2023-07-31 12:48 UTC, vboltrukanis commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/pages/desktop/CarinaHomePage.java
> +    public boolean isOverviewHeaderVisible() {
not proper name, or not proper actions inside of this method

2023-07-31 12:48 UTC, vboltrukanis commented on src/test/java/com/solvd/qa/carina/demo/ZebRunnerCarinaTest.java
> +        Assert.assertEquals(homePage.getHeader().isCarinaBrandDisplayed(), "Carina");
Add error message

2023-07-31 12:48 UTC, vboltrukanis commented on src/test/java/com/solvd/qa/carina/demo/ZebRunnerCarinaTest.java
> +public class ZebRunnerCarinaTest implements IAbstractTest {
You can combine small tests into one, so to decrease execution time of a suite

2023-07-31 22:27 UTC, zhyldyzMaks commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/footer/CarinaFooterMenuBase.java
> +public abstract class CarinaFooterMenuBase extends AbstractUIObject {
I just wanted to practice the abstract class logic in here. Removed

2023-08-02 05:29 UTC, zhyldyzMaks commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/header/CarinaHeaderPage.java
> +    public boolean isZebRunnerLogoDisplayed() {
Modified

2023-08-02 05:29 UTC, zhyldyzMaks commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/footer/CarinaFooterMenuBase.java
> +public abstract class CarinaFooterMenuBase extends AbstractUIObject {
Removed. It was created just to practice AbstractUIObject class

2023-08-02 05:30 UTC, zhyldyzMaks commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/header/CarinaHeaderPageBase.java
> +public abstract class CarinaHeaderPageBase extends AbstractUIObject {
Removed. Same as other Base classes

2023-08-02 05:36 UTC, zhyldyzMaks commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/header/CarinaHeaderPage.java
> +    public String isCarinaBrandDisplayed() {
Fixed

2023-08-02 06:04 UTC, zhyldyzMaks commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/header/CarinaHeaderPage.java
> +    public String getSearchText() {
Fixed

2023-08-02 06:04 UTC, zhyldyzMaks commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/pages/common/GitHubPageBase.java
> +public abstract class GitHubPageBase extends AbstractPage {
Removed

2023-08-02 06:05 UTC, zhyldyzMaks commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/pages/common/CarinaHomePageBase.java
> +public abstract class CarinaHomePageBase extends AbstractPage {
Removed

2023-08-02 06:18 UTC, zhyldyzMaks commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/navigation/CarinaNavigationPage.java
> +    public void clickGettingStartedLink() {
Fixed.

2023-08-02 06:51 UTC, zhyldyzMaks commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/navigation/CarinaNavigationPage.java
> +    public boolean isHighlighted() {
Done

2023-08-02 06:52 UTC, zhyldyzMaks commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/navigation/CarinaNavigationPage.java
> +    public boolean areElementsHidden() {
Changed to areNestedElementsHidden(){}

2023-08-02 08:02 UTC, zhyldyzMaks commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/pages/desktop/CarinaHomePage.java
> +    public boolean isOverviewHeaderVisible() {
Fixed

2023-08-02 08:03 UTC, zhyldyzMaks commented on src/test/java/com/solvd/qa/carina/demo/ZebRunnerCarinaTest.java
> +        Assert.assertEquals(homePage.getHeader().isCarinaBrandDisplayed(), "Carina");
Added

2023-08-02 08:06 UTC, zhyldyzMaks commented on src/test/java/com/solvd/qa/carina/demo/ZebRunnerCarinaTest.java
> +public class ZebRunnerCarinaTest implements IAbstractTest {
Combined tests related to header components validation into one test. 
Combined some tests related to navigation component into one test.

2023-08-02 08:23 UTC, zhyldyzMaks commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/navigation/CarinaNavigationPage.java
> +            if (allNavLinks.get(i).equals(dynamicXpathElement.format("md-nav__item md-nav__item--active")) || allNavLinks.get(i).equals(dynamicXpathElement.format("md-nav__item md-nav__item--active m
Changed with formatting the currentLink element before loop

2023-08-02 08:26 UTC, zhyldyzMaks commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/navigation/CarinaNavigationPage.java
> +    public void isLinkClickRedirectToProperPage(String expectedLink, String[] lists, boolean nested) {
Fixed

2023-08-02 08:27 UTC, zhyldyzMaks commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/navigation/CarinaNavigationPage.java
> +    public void isLinkClickRedirectToProperPage(String expectedLink, String[] lists, boolean nested) {
Changed function name

2023-08-04 13:45 UTC, vboltrukanis approved these changes
Apply all my suggestions and it is fine

2023-08-04 13:45 UTC, vboltrukanis commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/header/CarinaHeaderPage.java
> +public class CarinaHeaderPage extends AbstractUIObject {
Component not Page

2023-08-04 13:45 UTC, vboltrukanis commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/footerMenu/CarinaFooterMenu.java
> +    @FindBy(xpath = "//div[contains(text(),'2022 Zebrunner')]")
Locators inside of componets should start with . mostly, so to search not entire page, but only as a part of component

2023-08-04 13:45 UTC, vboltrukanis commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/header/CarinaHeaderPage.java
> +    public boolean isCarinaBrandDisplayed() {
Name and actions are not equal.
Better use `getBrandText()` method

2023-08-04 13:45 UTC, vboltrukanis commented on src/main/java/com/solvd/qa/carina/demo/zebrunner/web/components/navigationMenu/CarinaNavigationPage.java
> +public class CarinaNavigationPage extends AbstractUIObject {
Conponent

2023-08-04 13:45 UTC, vboltrukanis commented on src/test/java/com/solvd/qa/carina/demo/ZebRunnerCarinaTest.java
> +        Assert.assertTrue(homePage.getSearchComponentObject().isSearchComponentDisplayed(),
Use softAssert here

2023-08-04 21:46 UTC, zhyldyzMaks commented
Merge 'web-automation-zebrunner' branch into main branch

2023-08-04 21:46 UTC, merged